project:
  type: website

website:
  title: "HNU3000_projet"
  site-url: 
  site-path: 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

