project:
  type: website

website:
  title: "HNU3000_projet"
  description: "Mon projet pour le cours HNU3000"
  reader-mode: true
  site-url: https://amelie-lr.github.io/hnu3000_projet/
  repo-url: https://github.com/amelie-lr/hnu3000_projet
  repo-actions: [edit, issue, source]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  freeze: auto
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

